config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#new'
  # get  "articles/index"  => "articles#index"
                            # 動画投稿フォーム　処理　一覧
  resources :posts, only: %i(new create index edit update destroy)

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
# 　投稿する動画　　　存在
  validates :video, presence: true
#   関連付け　　　動画タイトル説明動画　インターネット上のファイル置き場
  mount_uploader :video, VideoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set, only: [:edit,:update,:destroy]
# 動画投稿フォーム
  def new
    @post = Post.new
  end
# 動画　処理
  def create
# 　動画のタイトル、説明、動画
    @post = Post.new(post_params)
    if @post.save
      redirect_to :action => 'index' ,notice: '投稿しました'
    else
# 　動画投稿ページ
      render :new
    end
  end
  
#   投稿一覧
  def index
# 			投稿フォーム　投稿処理	投稿一覧ページ　全て　並べる　新規作成順
    @posts = Post.all.order('created_at DESC')
  end
  # 編集
  def edit
    # @post = Post.find_by(id: params[:id])
  end
# 　編集投稿処理
  def update
    if @post.update(post_params)
      redirect_to :action => 'index' ,notice: '編集しました'
    else
      render action: :edit
    end
  end
# 　投稿処理
  def destroy
    @post.destroy
   redirect_to :action => 'index' ,notice: '消去しました'
  end

  private
    def post_params
# 　　　動画タイトル　説明　動画
      params.require(:post).permit(:title, :body, :video,:heroku_url,:github_url)
    end
    
  def set
    @post = Post.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"
 
def text_url_to_link text
 
  URI.extract(text, ['http','https'] ).uniq.each do |url|
    sub_text = ""
    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
 
    text.gsub!(url, sub_text)
  end
 
  return text
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!--タイトル-->
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
<!--ビデオ-->
  <div class="field">
    <%= form.label :video %>
                                   <!--ファイル種類動画-->
    <%= f.file_field :video, :accept => 'video/*' %>
  </div>
<!--送信ボタン-->
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.video %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Video:</strong>
  <%= @article.video %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
      <ul class="navbar-nav mr-auto ">
      </ul>
      <ul class="mr-4 navbar-nav">
         <%= link_to '新規作成',new_post_path %>
      </ul>
      <ul class="navbar-nav">
         <%= link_to '動画一覧',posts_path %>
      </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

    <!--真ん中に寄せる-->
  <div class="container">
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!--rails フォームタグ　動画のタイトル、動画の説明、投稿する動画-->
<%= form_with(model: @post, url: { action: :update },local: true) do |form| %>
<!--タイトル-->
  <div class="form-group">
    <%= form.text_field :title, placeholder: "タイトル" %>
  </div>
  <div class="form-group">
    <%= form.text_field :github_url, placeholder: "github_url" %>  </div>
  <div class="form-group">
    <%= form.text_field :heroku_url, placeholder: "heroku_url" %>  </div>
<!--動画説明-->
  <div class="form-group">
    <%= form.text_area :body, placeholder: "動画の説明" %>
  </div>
<!--ファイル投稿-->
  <div class="form-group">
    <%= form.file_field :video , :accept => 'video/*'%>
  </div>
    <button type="submit" class="btn btn-primary">編集する</button>
<% end %>

app/views/posts/index.html.erb
<ul class="list-unstyled">
  <% @posts.each do |post| %>
  <li class="media">
    <!--ビデオタグ　モデル　カラム　文字以外を文字にする　-->
    <%= video_tag post.video.to_s, :size => "1000x1000" , loop: true, autoplay: true ,muted: true%>
    <div class="media-body">
      <h6 class="mt-0 mb-1">[タイトル]<br></h6>
      <%= post.title %>
      <h6 class="mt-0 mb-1">[github_url]<br></h6>
      <div class="link">
　　　<%= text_url_to_link(h(post.github_url)).html_safe %>
　　　</div>
      <h6 class="mt-0 mb-1">[heroku_url]<br></h6>
      <%= post.heroku_url %>
      <h6 class="mt-0 mb-1">[アプリ説明]<br></h6>
      <%= simple_format(post.body) %>
      <%= link_to "編集",  edit_post_path(post) %>
      <%= link_to "削除", post, method: :delete, data: { confirm: "#{post.title}を削除して大丈夫ですか？" } %>
    </div>
   
  </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<!--rails フォームタグ　動画のタイトル、動画の説明、投稿する動画-->
<%= form_with(model: @post, local: true) do |form| %>
<!--タイトル-->
  <div class="form-group">
    <%= form.text_field :title, placeholder: "タイトル" %>  </div>
  <div class="form-group">
    <%= form.text_field :github_url, placeholder: "github_url" %>  </div>
  <div class="form-group">
    <%= form.text_field :heroku_url, placeholder: "heroku_url" %>  </div>
<!--動画説明-->
  <div class="form-group">
    <%= form.text_area :body, placeholder: "動画の説明" %>
  </div>
<!--ファイル投稿-->
  <div class="form-group">
    <%= form.file_field :video , :accept => 'video/*'%>
  </div>
    <button type="submit" class="btn btn-primary">Submit</button>
<% end %>